name: Expo Auto Deployment

on:
  push:
    branches: [ main ]  # or your primary branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment (optional but recommended)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # specify a version compatible with Expo

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Publish to Expo using the secret token
      - name: Publish to Expo
        run: npx expo publish
        env:
          EXPO_TOKEN: ${{ secrets.GitHub_CI_Token }}
