
name: Expo Auto Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Publish to Expo
        run: npx expo publish
        env:
          EXPO_TOKEN: ${{ secrets.GitHub CI Token }}
