name: Expo Auto Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js (using version 16)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm install

      - name: Publish to Expo
        run: npx expo publish
        env:
          EXPO_TOKEN: ${{ secrets.GitHub_CI_Token }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          EXPO_TOKEN: ${{ secrets.GitHub_CI_Token }}

          publish_dir: ./web-build
